description: HypnoPitch — pattern sequencer and audio app.
environment:
  sdk: '>=3.4.4 <4.0.0'
version: 1.1.2+30

flutter:
  assets:
    - samples/Acoustic/
    - samples/Acoustic/Orchestral/
    - samples/Drums/
    - samples/Drums/Acoustic/
    - samples/Drums/Acoustic/Kick/
    - samples/Drums/Acoustic/Plates/
    - samples/Drums/Acoustic/Plates/China/
    - samples/Drums/Acoustic/Plates/Crash/
    - samples/Drums/Acoustic/Plates/Hi Hat/
    - samples/Drums/Acoustic/Plates/Ride Cymbal/
    - samples/Drums/Acoustic/Plates/Splash/
    - samples/Drums/Acoustic/Snare/
    - samples/Drums/Acoustic/Toms/
    - samples/Drums/Electronic/
    - samples/Drums/Electronic/Kick/
    - samples/Drums/Electronic/Plates/
    - samples/Drums/Electronic/Plates/Hi-Hat/
    - samples/Drums/Electronic/Snare/
    - samples/Drums/Electronic/Toms/
    - samples/Noise/
    - samples/Noise/Clicks/
    - samples/Noise/Other/
    - samples/Synth/
    - samples/Synth/Bass/
    - samples/Synth/High/
    - samples/Synth/High/Distorted/
    - samples/Synth/High/Minimal/
    - samples/Synth/High/Pads/
    - .env
    - icons/
    - samples_manifest.json
  uses-material-design: true
dependencies:
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  file_picker: ^8.0.7
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  ffi: ^2.1.0
  path: ^1.9.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  crypto: ^3.0.5
  wheel_chooser: ^1.1.2
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.2
  archive: ^4.0.9
name: hypnopitch
publish_to: none
dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^13.0.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/white_mane1_cut_2.png"
  remove_alpha_ios: true
